server:
  port: 8080

spring:
  application:
    name: api-gateway
    version: 1.0-SNAPSHOT
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraudService
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/*

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true